My quizzes
elacymerys/thesis pull request #32
Opened 2022-11-19 17:15 UTC by elacymerys

Create My Quizzes page template for teacher's view

2022-11-22 20:11 UTC, MaksymilianK requested changes

2022-11-22 20:11 UTC, MaksymilianK commented on thesis-gui/src/components/my-quizzes/MyQuizzes.tsx
> +        return <QuizzesListItem name={ quiz.name } questionsNumber={ quiz.questionsNumber } />
Can be simplified by removing `return`.

2022-11-22 20:11 UTC, MaksymilianK commented on thesis-gui/src/components/my-quizzes/MyQuizzes.tsx
> +    return (
same as above

2022-11-22 20:11 UTC, MaksymilianK commented on thesis-gui/src/components/my-quizzes/QuizCreator.tsx
> +        return <AnswerInputItem answerNumber={ answerNumber } />
Can be simplified by removing `return`.

2022-11-22 20:11 UTC, MaksymilianK commented on thesis-gui/src/components/my-quizzes/QuizCreator.tsx
> +    const answerInputItems = Array.from({ length: 4 }, (_, i) => i + 1).map(answerNumber => {
I didn't know that we can generate an Array of numbers in JS this way, so I learned something new :) . But to be honest, for such a small array `[0,1,2,3].map(...` looks more readable :) .

2022-11-23 11:00 UTC, elacymerys commented on thesis-gui/src/components/my-quizzes/MyQuizzes.tsx
> +    return (
?

2022-11-23 16:05 UTC, MaksymilianK commented on thesis-gui/src/components/my-quizzes/MyQuizzes.tsx
> +    return (
`return `can be removed

2022-11-23 16:07 UTC, MaksymilianK submitted a review, later dismissed

2022-11-24 15:33 UTC, MaksymilianK approved these changes

2022-11-25 19:02 UTC, merged