Quiz Creator
elacymerys/thesis pull request #41
Opened 2022-12-03 18:37 UTC by MaksymilianK

2022-12-09 22:43 UTC, elacymerys commented
Is there a quick way to disable adding new question when the current one is empty? It's not very important functionality to do now but a user can create many empty questions without getting any error and then when he/she wants to save a quiz the error message states that he/she should first fix all the errors (but there's not any error).

2022-12-09 22:50 UTC, elacymerys commented
Also not something urgent but I think it would be a good idea to add confirmation of question deletion.

2022-12-10 11:47 UTC, elacymerys requested changes

2022-12-10 11:47 UTC, elacymerys commented on thesis-gui/src/utils/validators.ts
> +    if (!question || question.length < 2 || question.length > 200) {
Shouldn't be here `question.length < 1` instead of `question.length < 2` as the error message states that 'Question must be **1-200** characters long'?

2022-12-10 11:47 UTC, elacymerys commented on thesis-gui/src/utils/validators.ts
> +    if (!answer || answer.length < 2 || answer.length > 50) {
Same as above

2022-12-10 11:47 UTC, elacymerys commented on thesis-gui/src/utils/validators.ts
> +    if (!answer || answer.length < 2 || answer.length > 50) {
Same as above

2022-12-10 11:47 UTC, elacymerys commented on thesis-gui/tsconfig.json
> +    "jsx": "preserve"
Just out of my curiosity and to learn something new ;-) - why was this change needed?

2022-12-10 11:47 UTC, elacymerys commented on thesis-gui/src/types/my-quizz.ts
> +    teacherQuestionsRequest: Question
Shouldn't it be a list of questions in set - `Question[]` instead of `Question`?

2022-12-10 11:47 UTC, elacymerys commented on thesis-gui/src/components/my-quizzes/quiz-builder/AnswersInput.tsx
> +                    placeholder={ `Enter answer ${answerNumber}` }
Please change `Enter answer ${answerNumber}` to `Enter answer ${answerNumber+1}`. I think it will be more natural for a user ;-)

2022-12-10 11:47 UTC, elacymerys commented on thesis-gui/src/components/my-quizzes/quiz-builder/QuizBuilder.tsx
> +            </div>
I would replace the whole `div` with its content with 
`
<IonToolbar>
                <IonTitle className="ion-padding">Question {currentQuestionNumber + 1}</IonTitle>
                <IonButtons slot="primary">
                    <IonButton
                        disabled={questions.length < 2}
                        onClick={handleDelete}
                    >
                        <IonIcon slot="icon-only" icon={trashBin} />
                    </IonButton>
                </IonButtons>
            </IonToolbar>
` 
When there's only icon as button content it looks better with `slot="icon-only"`

2022-12-10 11:57 UTC, MaksymilianK commented on thesis-gui/tsconfig.json
> +    "jsx": "preserve"
Honestly, I have no idea :) . It has probably changed when I ran `npm install` or something. I'll just roll it back.

2022-12-10 11:59 UTC, MaksymilianK commented on thesis-gui/src/types/my-quizz.ts
> +    teacherQuestionsRequest: Question
Yes, you're right. But, I can see now that these types aren't currently used anywhere (except `QuestionForm`), so I'll just remove them from this PR.

2022-12-10 12:01 UTC, MaksymilianK commented on thesis-gui/src/components/my-quizzes/quiz-builder/AnswersInput.tsx
> +                    placeholder={ `Enter answer ${answerNumber}` }
Good idea! Done.

2022-12-10 12:07 UTC, MaksymilianK commented on thesis-gui/src/components/my-quizzes/quiz-builder/QuizBuilder.tsx
> +            </div>
Nice, looks much better now :)

2022-12-10 12:07 UTC, MaksymilianK commented on thesis-gui/src/utils/validators.ts
> +    if (!answer || answer.length < 2 || answer.length > 50) {
Done

2022-12-10 12:07 UTC, MaksymilianK commented on thesis-gui/src/utils/validators.ts
> +    if (!answer || answer.length < 2 || answer.length > 50) {
Done

2022-12-10 12:07 UTC, MaksymilianK commented on thesis-gui/src/utils/validators.ts
> +    if (!question || question.length < 2 || question.length > 200) {
Yes, you're right. Done.

2022-12-10 15:43 UTC, elacymerys approved these changes

2022-12-10 15:43 UTC, merged